### ISSUE TITLE
[BUG - Release] UE 4.14 Game crashes on startup with UE4SS

### ISSUE THREAD

**Issue by Marold57** [UE4SS-RE/RE-UE4SS#438] opened 2024-03-16 10:51 UTC
**Branch or Release**
v3.0.1

**Game and Engine Version**
Space Hulk: Deathwing Enhanced Edition (Steam Version) Unreal Engine 4.14.3

**Describe the bug**
Game crashes at startup. Only the splash screen runs for 2 seconds and then crashes and the UE Crash Reporter opens.

**Mods directory**
No mods.

**To Reproduce**
1. Launch game
2. Splash Screen runs for 2 seconds. Game crashes.
3. UE4 Crash Reporter opens

**Screenshots, UE4SS Log, and .dmp file**
Screenshots, logs and .dmp files are attached as zip files.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

[Space Hulk Deathwing UE 4.14.3.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14623290/Space.Hulk.Deathwing.UE.4.14.3.zip)

**Comment by bitonality** [comment] 2024-03-20 21:42
@Marold57  Would it be possible to get a Space Hulk game log without UE4SS installed? I'm curious to see what the log file looks like on a clean launch of the game.

**Comment by Marold57** [comment] 2024-03-21 13:41
[SpaceHulkGame.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14695938/SpaceHulkGame.log)
@bitonality 
Clean log from the Support Branch without UE4SS and without mods.
Started a mission and played until the first objective and then closed the game.

**Comment by bitonality** [comment] 2024-03-21 22:56
Do you have the ability to build UE4SS from source?

I have a hunch that this is due to the #414 FUrl struct member layout changes in internal UE code.

If you can re-arrange the FUrl struct in UE4SS to match UE 4.14.3 and compile UE4SS you could see if that unblocks you.

UE4.14.3 FUrl def
```cpp
//URL structure.
USTRUCT()
struct ENGINE_API FURL
{
	GENERATED_USTRUCT_BODY()

	// Protocol, i.e. "unreal" or "http".
	UPROPERTY()
	FString Protocol;

	// Optional hostname, i.e. "204.157.115.40" or "unreal.epicgames.com", blank if local.
	UPROPERTY()
	FString Host;

	// Optional host port.
	UPROPERTY()
	int32 Port;

	// Map name, i.e. "SkyCity", default is "Entry".
	UPROPERTY()
	FString Map;

	// Optional place to download Map if client does not possess it
	UPROPERTY()
	FString RedirectURL;

	// Options.
	UPROPERTY()
	TArray<FString> Op;

	// Portal to enter through, default is "".
	UPROPERTY()
	FString Portal;

	UPROPERTY()
	int32 Valid;
```

**Comment by Marold57** [comment] 2024-03-21 23:06
I'm not familiar with it myself, but I'll can ask on my discord server if someone can take care of it.

**Comment by UE4SS** [comment] 2024-03-22 20:01
Here's a build of 3.0.1 with the described `FURL` changes: [UE4SS_FURL_for_UE4.14.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14727897/UE4SS_FURL_for_UE4.14.zip)

**Comment by Marold57** [comment] 2024-03-23 10:32
[Logs and dmp and Screenshot.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14731189/Logs.and.dmp.and.Screenshot.zip)
Unfortunately it still crashes on startup with the FURL changes.

**Comment by UE4SS** [comment] 2024-03-23 14:20
Is there no .dmp file in the Win64 directory, where UE4SS.dll is located ?
These UE4Minidump files don't work and I think they are generated by the game itself, not from UE4SS.
In all cases so far (including yours), the call stack is unavailable due to various missing binaries.
The .dmp file in the same directory as UE4SS.dll is generated by UE4SS and don't generally require any extra binaries to be useful.
If no .dmp file is available, that doesn't leave us with many ways to determine what the problem is beyond guessing unless we just happen to actually have the game and unfortunately I don't.

**Comment by Marold57** [comment] 2024-03-23 14:56
UE4SS does not create a .dmp file.
I have set in UE4SS-settings.ini:
[CrashDump]
EnableDumping = 1
FullMemoryDump = 0

and tried:
[CrashDump]
EnableDumping = 1
FullMemoryDump = 1

but still no .dmp file is created where UE4SS.dll is located.
![NoDmpFile](https://github.com/UE4SS-RE/RE-UE4SS/assets/85793314/ac9b0494-2a52-4f3b-926a-0aaa1ced0d06)


If needed I could give a Steam EU key for the game.

**Comment by UE4SS** [comment] 2024-03-23 15:09
It's possible this is the same problem as #410.
Try this solution: https://github.com/UE4SS-RE/RE-UE4SS/issues/410#issuecomment-1971861346
Even if you want BP mods to load, this will tell us if it's the same problem.
If it is the same problem, that means you (or someone else) needs to reverse engineer the vtable for the `UEngine` class and follow [these](https://github.com/UE4SS-RE/RE-UE4SS/issues/410#issuecomment-1971804051) instructions to update the representation of the vtable that UE4SS uses.

**Comment by Marold57** [comment] 2024-03-23 16:16
That worked. No crash and I can also open the UE4SS console ingame. But that means for blueprint modding someone has to reverse engineer the vatble for UEngine?

**Comment by UE4SS** [comment] 2024-03-23 18:04
You can solve this with trial & error by doing the same thing they did in #410 and just download VTableLayout.ini for your engine version and add a new line at the beginning of the UEngine section.
If it doesn't work, add another line, and keep going until it works.
After that, you'll need re-enable LoadMap in UE4SS-settings.ini.

**Comment by UE4SS** [comment] 2024-03-23 18:09
Closing because this problem is caused by custom engine changes, not by a bug in UE4SS, and a solution has been found and provided.
If someone does the reverse engineering work at some point, we can include the required VTableLayout.ini file in CustomGamesConfigs.zip.

**Closed by UE4SS** 2024-03-23 18:09 UTC
