### ISSUE TITLE
[BUG - Release] UnregisterHook not correctly follow the given preID/postID

### ISSUE THREAD

**Issue by wjm** [UE4SS-RE/RE-UE4SS#305] opened 2024-01-23 18:04 UTC
**Branch or Release**
2.5.2

**Game and Engine Version**
Game where the bug occurred, and the UE engine version of the game.

**Describe the bug**
When trying to unregisterhook, the provided postid is different from the log, e.g. in the log after it print [17:55:38] [Lua] 34 in theory the unregisterhook should unregister with post-id:4 and pre-id:4, but it still says 1 and 2

**To Reproduce**
```
local luck=false
local preId, postId = nil
local preId2, postId2 = nil
RegisterKeyBind(Key.F7, {}, function()
  luck = not luck
  print("luck"..tostring(luck))

  if luck then
    preId, postId = RegisterHook("/Script/Pal.PalGameSetting:GetCaptureLevelBySphereType", function(Context,SphereType)
      print("Hooked CalcCaptureRate")
      return 65536
    end)
    preId2, postId2 = RegisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", function(Context,TargetPal)
       print("hooked rate")
       return 100.0
     end)
     print(tostring(preId)..tostring(postId))
  else
    print("luck off")
    UnregisterHook("/Script/Pal.PalGameSetting:GetCaptureLevelBySphereType", preId, postId)
    UnregisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", preId2, postId2)
  end
end)
```

**Expected behavior**
unregisterhook unregister the correct preID/postID

**Screenshots and UE4SS Log**
[17:55:37] [Lua] lucktrue
[17:55:37] [RegisterHook] Registered native hook (1, 2) for Function /Script/Pal.PalGameSetting:GetCaptureLevelBySphereType
[17:55:37] [RegisterHook] Registered native hook (1, 2) for Function /Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP
[17:55:37] [Lua] 12
[17:55:37] [Lua] luck off
[17:55:37] Unregistering hook with pre-id: 1
[17:55:37] Unregistering hook with post-id: 2
[17:55:37] Unregistering hook with pre-id: 1
[17:55:37] Unregistering hook with post-id: 2
[17:55:38] [Lua] lucktrue
[17:55:38] [RegisterHook] Registered native hook (3, 4) for Function /Script/Pal.PalGameSetting:GetCaptureLevelBySphereType
[17:55:38] [RegisterHook] Registered native hook (3, 4) for Function /Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP
[17:55:38] [Lua] 34
[17:55:39] [Lua] luckfalse
[17:55:39] [Lua] luck off
[17:55:39] Unregistering hook with pre-id: 1
[17:55:39] Unregistering hook with post-id: 2
[17:55:39] Unregistering hook with pre-id: 1
[17:55:39] Unregistering hook with post-id: 2

**Desktop:**
 - OS: Win10

**Additional context**
If trigger the keybind more, some time it will increase the unregistering hook preId/postId, which I'm not sure how it happened.

**Comment by UE4SS** [comment] 2024-01-23 21:14
I believe `UnregisterHook` doesn't work properly in 2.5.2, but it should be fixed for the next release.
If you want to try the fixed version before the next release, you can try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-570-g37e727b.zip
With this build you'll need both dwmapi.dll and UE4SS.dll from the zip file.

**Comment by wjm** [comment] 2024-01-23 21:39
> I believe `UnregisterHook` doesn't work properly in 2.5.2, but it should be fixed for the next release. If you want to try the fixed version before the next release, you can try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-570-g37e727b.zip With this build you'll need both dwmapi.dll and UE4SS.dll from the zip file.

Thanks. I'll try the experimental version later and update the feedback. Also, may I ask if is there an easy way to find the original result returned by the function, and is that possible for me to use the lua to get the traceback(call stack) for a function?

**Comment by UE4SS** [comment] 2024-01-23 21:50
> > I believe `UnregisterHook` doesn't work properly in 2.5.2, but it should be fixed for the next release. If you want to try the fixed version before the next release, you can try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-570-g37e727b.zip With this build you'll need both dwmapi.dll and UE4SS.dll from the zip file.
> 
> Thanks. I'll try the experimental version later and update the feedback. Also, may I ask if is there an easy way to find the original result returned by the function, and is that possible for me to use the lua to get the traceback(call stack) for a function?

There is no way to access the return value from the original function currently.
In the experimental build, you can provide a second function to `RegisterHook` to act as a post-hook, but unfortunately it doesn't provide the return value from the original function, however, that shouldn't be too difficult to implement and I'm gonna have a look at it and I'll reply with a link to the experimental build if/when it's available.

I don't believe there's any way to get the native call stack from within Lua.

**Comment by UE4SS** [comment] 2024-01-23 22:40
Here's the experimental build containing a way to access the original return value: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-574-g1e728f2.zip
For an example, see: https://github.com/UE4SS-RE/RE-UE4SS/pull/306

**Comment by wjm** [comment] 2024-01-24 00:02
> Here's the experimental build containing a way to access the original return value: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-574-g1e728f2.zip For an example, see: #306

Thanks for the update, now UnregisterHook works fine for me.

For the return value, I think there might be a type in the example code, 

```
RegisterHook("/Script/Engine.Character:CanJumpInternal", function()
    -- Some code.
end), function(ParamContext, ParamReturnValue)
    -- This value will be the original return value in the case where the pre-hook didn't modify it.
    -- It will be the modification done by the pre-hook otherwise.
    print(string.format("Return Value: %s\n", ParamReturnValue:get()))
end)
```

I think after the first end there shouldn't be a `)`, or else I think it will be a syntax error for Lua.

I tried the new release but I got 
```
 Error executing hook post-callback /Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP: [Lua::call_function] lua_pcall returned LUA_ERRRUN => attempt to call a RemoteUnrealParam value
```

in the log now. Here is my code

```
RegisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", function(Context,TargetPal)
      print("hooked rate")
      return 100.0
    end,function(ParamContext, ParamReturnValue)
      print(string.format("Return Value: %s\n", ParamReturnValue:get()))
    end)
```

**Comment by UE4SS** [comment] 2024-01-24 09:48
> > Here's the experimental build containing a way to access the original return value: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-574-g1e728f2.zip For an example, see: #306
> 
> Thanks for the update, now UnregisterHook works fine for me.
> 
> For the return value, I think there might be a type in the example code,
> 
> ```
> RegisterHook("/Script/Engine.Character:CanJumpInternal", function()
>     -- Some code.
> end), function(ParamContext, ParamReturnValue)
>     -- This value will be the original return value in the case where the pre-hook didn't modify it.
>     -- It will be the modification done by the pre-hook otherwise.
>     print(string.format("Return Value: %s\n", ParamReturnValue:get()))
> end)
> ```
> 
> I think after the first end there shouldn't be a `)`, or else I think it will be a syntax error for Lua.
> 
> I tried the new release but I got
> 
> ```
>  Error executing hook post-callback /Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP: [Lua::call_function] lua_pcall returned LUA_ERRRUN => attempt to call a RemoteUnrealParam value
> ```
> 
> in the log now. Here is my code
> 
> ```
> RegisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", function(Context,TargetPal)
>       print("hooked rate")
>       return 100.0
>     end,function(ParamContext, ParamReturnValue)
>       print(string.format("Return Value: %s\n", ParamReturnValue:get()))
>     end)
> ```

There was a `)` after the first `end` which shouldn't have been there, thanks.
I'm unfortunately unable to reproduce your error with the code you supplied.

**Comment by UE4SS** [comment] 2024-01-24 14:39
The `RemoteUnrealParam` error should be fixed now.
Please try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-576-g4e9dc1e.zip

**Comment by wjm** [comment] 2024-01-24 23:32
> The `RemoteUnrealParam` error should be fixed now. Please try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-576-g4e9dc1e.zip

Thanks! It is working perfectly! Just a quick question, if the return value was modified in the prehook, is it the intended design that the posthook can only get the modified value?

```
RegisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", 
    function(Context,TargetPal)
      return 100.0
    end,
    function(ParamContext, ParamReturnValue)
      print(string.format("Return Value: %s\n", ParamReturnValue:get()))
    end)
```

For example, if I'm using the above code, the Return Value will always printed as 100.0 despite the original return value.

**Comment by UE4SS** [comment] 2024-01-25 11:52
> > The `RemoteUnrealParam` error should be fixed now. Please try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-576-g4e9dc1e.zip
> 
> Thanks! It is working perfectly! Just a quick question, if the return value was modified in the prehook, is it the intended design that the posthook can only get the modified value?
> 
> ```
> RegisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", 
>     function(Context,TargetPal)
>       return 100.0
>     end,
>     function(ParamContext, ParamReturnValue)
>       print(string.format("Return Value: %s\n", ParamReturnValue:get()))
>     end)
> ```
> 
> For example, if I'm using the above code, the Return Value will always printed as 100.0 despite the original return value.

This has now been changed.
The return passed as the second param to the second callback will now always be the original return value regardless of changes have been made to it in the first callback.
Experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-577-gddee25c.zip

**Comment by wjm** [comment] 2024-01-26 04:07
> > > The `RemoteUnrealParam` error should be fixed now. Please try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-576-g4e9dc1e.zip
> > 
> > 
> > Thanks! It is working perfectly! Just a quick question, if the return value was modified in the prehook, is it the intended design that the posthook can only get the modified value?
> > ```
> > RegisterHook("/Script/Pal.PalGameSetting:GetCaptureRateByStatus_ForGameSettingBP", 
> >     function(Context,TargetPal)
> >       return 100.0
> >     end,
> >     function(ParamContext, ParamReturnValue)
> >       print(string.format("Return Value: %s\n", ParamReturnValue:get()))
> >     end)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For example, if I'm using the above code, the Return Value will always printed as 100.0 despite the original return value.
> 
> This has now been changed. The return value passed as the second param to the second callback will now always be the original return value regardless if changes have been made to it in the first callback. Experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-577-gddee25c.zip

Just tested and it works perfectly! Thanks a lot for the tool

**Closed** 2024-01-26 12:07 UTC
