### ISSUE TITLE
[BUG - Release] Crash when exiting game with watches to be logged to file

### ISSUE THREAD

**Issue by Buckminsterfullerene02** [UE4SS-RE/RE-UE4SS#418] opened 2024-02-29 23:19 UTC
**Branch or Release**
3.0.1

**Game and Engine Version**
Deep Rock Galactic, 4.27

**Describe the bug**
Everything running as normal, using watches on some stuff fine, with logging to file selected. But when I close the game, I get a crash dmp and none of the data that was sent to the watches on the GUI was output into any file. I thought it's meant to get sent to watches.meta.json but that file seems to only be populated when you save a watch to be auto set when you next load up the game.

**Mods directory**
No mods installed.

**To Reproduce**
It's a bit odd, I cannot reliably repro the crash part issue with the same setup steps as below, however my watched data (except saving watch for auto-load) are never saved to any file.

1. Launch game
2. Add watch to `/Script/GameplayCameras.MatineeCameraShake:ReceiveIsFinished`
3. Load into mission (so there's a few entries in there)
4. Exit game
5. Crash (sometimes)

**Expected behavior**
Game to not crash, and the write to file setting on a watch to actually write the data to a file.

**Screenshots, UE4SS Log, and .dmp file**
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14454514/UE4SS.log)

[crash_2024_02_29_22_57_44.dmp](https://cdn.discordapp.com/attachments/1109192354595876944/1212901970092888064/crash_2024_02_29_22_57_44.dmp?ex=65f385fc&is=65e110fc&hm=329e039933dee73c3b5d56003f202f2defe9f341ae0c23a54bde4d2749ef5493&)

**Desktop:**
 - OS: Win10

**Comment by UE4SS** [comment] 2024-03-01 00:40
I'm able to reproduce both the crash and the fact that it's not being written to file.

**Comment by UE4SS** [comment] 2024-03-01 00:43
The `watches.meta.json` file is not meant to receive logs of whatever the user watches, it just stores metadata for automatically regaining a watch if the user ticks "Auto-create on startup" checkbox to the right of the watch name.

**Comment by UE4SS** [comment] 2024-03-01 00:47
I don't yet know why it's crashing, but it's not saving to file because it appears that the feature was only implemented for properties.
This shouldn't be very hard to implement for functions, give me a few moments.

**Comment by UE4SS** [comment] 2024-03-01 00:56
The watches not working on functions is addressed by #419

**Comment by UE4SS** [comment] 2024-03-01 01:03
#419 hopefully now also fixes the crash.

**Comment by UE4SS** [comment] 2024-03-01 16:11
> > it appears that the feature was only implemented for properties.
> 
> Is it intentional that I can't set a watch on an array property? But I can set a watch on any other property type.

Yes, ArrayProperty and also StructProperty watches have not been implemented, not sure why.
There doesn't appear to be any problems with StructProperty.
I'm not aware of any ArrayProperties in defualt UE that I can test with but I'll add both StructProperty and ArrayProperty to #419 and you can test it and let me know if it works.

**Comment by Buckminsterfullerene02** [comment] 2024-03-03 21:13
> > > it appears that the feature was only implemented for properties.
> > 
> > 
> > Is it intentional that I can't set a watch on an array property? But I can set a watch on any other property type.
> 
> Yes, ArrayProperty and also StructProperty watches have not been implemented, not sure why. There doesn't appear to be any problems with StructProperty. I'm not aware of any ArrayProperties in defualt UE that I can test with but I'll add both StructProperty and ArrayProperty to #419 and you can test it and let me know if it works.

Forgot to reply, they do seem to work.

**Comment by UE4SS** [comment] 2024-03-03 22:18
This crash is caused by watches being processed after UE has started shutting down and freeing objects which means the functions and properties being watched might not exist any longer.
The changes introduced by #419 might make this happen a bit less often but it will still happen.
I'm not sure how to properly fix this problem without using the GUObjectArray lock.

**Comment by UE4SS** [comment] 2024-03-03 23:48
To clarify, `FUObjectArray::ObjObjectsCritical` is not enough.
That lock isn't locked when UE shuts down.
I think we need `FGCCSyncObject::Critical`, and I'm not sure we can access that very easily.
We can maybe use `FUObjectArray::UObjectDeleteListenersCritical` because that's locked when UObjectArray shuts down but it might already be too late, not sure.
It would be easier to access than `FGCCSyncObject::Critical` because we already implement FUObjectArray, all we need to do is add it to UVTD, and it's right after `UObjectDeleteListeners` which we already implement.

**Closed** 2024-03-26 15:36 UTC
